# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e80198d641f38a5aac9ea98a93253d2bfb462ad565d4a8f6582cd084b5dbcc9908fac85abd7718a909eea81982d3ee56ddc7a920a9b0679de45f607a220f447

test:
  secret_key_base: bf75eb29a08747890c88739455f0451ff43393d2e474c97a00c5c6a7f921c2f0bc4069cb6760e23b93b88c9e66eb5ae8099e04620ef13ec36523ffea4771ca9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
